package dev.astronauta.dbeaverMCP.db;

import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.jkiss.dbeaver.model.DBPScriptObject;
import org.jkiss.dbeaver.model.DBUtils;
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
import org.jkiss.dbeaver.model.struct.DBSAttributeBase;
import org.jkiss.dbeaver.model.struct.rdb.DBSCatalog;
import org.jkiss.dbeaver.model.struct.DBSEntity;
import org.jkiss.dbeaver.model.struct.DBSEntityAssociation;
import org.jkiss.dbeaver.model.struct.DBSEntityAttribute;
import org.jkiss.dbeaver.model.struct.DBSEntityAttributeRef;
import org.jkiss.dbeaver.model.struct.DBSEntityConstraint;
import org.jkiss.dbeaver.model.struct.DBSEntityReferrer;
import org.jkiss.dbeaver.model.struct.DBSObject;
import org.jkiss.dbeaver.model.struct.DBSObjectContainer;
import org.jkiss.dbeaver.model.struct.rdb.DBSSchema;
import org.jkiss.dbeaver.model.struct.rdb.DBSProcedure;
import org.jkiss.dbeaver.model.struct.rdb.DBSProcedureParameter;
import org.jkiss.dbeaver.model.struct.rdb.DBSTableIndex;
import org.jkiss.dbeaver.model.struct.rdb.DBSTrigger;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/** Maps DBeaver objects to metadata responses; partial failures include warnings. */
final class MetadataMapper {
    private static final Logger LOG = LoggerFactory.getLogger(MetadataMapper.class);

    private MetadataMapper() {
    }

    static String displayPath(DBSObjectContainer root, DBSObject object) {
        if (object == root) {
            return "(connection root)";
        }
        List<String> parts = new ArrayList<>();
        for (DBSObject current = object; current != null && current != root; current = current.getParentObject()) {
            parts.add(0, current.getName());
        }
        return String.join("/", parts);
    }

    static Map<String, Object> describeObject(DBSObject object) {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("name", object.getName());
        String kind;
        if (object instanceof DBSEntity entity) {
            kind = "entity:" + safe(() -> entity.getEntityType().getId(), "entity");
        } else if (object instanceof DBSProcedure) {
            kind = "procedure";
        } else if (object instanceof DBSTrigger) {
            kind = "trigger";
        } else if (object instanceof DBSObjectContainer) {
            kind = "container";
        } else {
            kind = "object";
        }
        map.put("kind", kind);
        map.put("type", object.getClass().getSimpleName());
        put(map, "description", safe(object::getDescription));
        map.put("navigable", object instanceof DBSObjectContainer);
        return map;
    }

    static Map<String, Object> describeAttribute(DBSEntityAttribute attr) {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("name", attr.getName());
        put(map, "ordinal", safe(() -> ((DBSAttributeBase) attr).getOrdinalPosition() + 1));
        put(map, "type", safe(attr::getTypeName));
        put(map, "fullType", safe(attr::getFullTypeName));
        put(map, "typeId", safe(attr::getTypeID));
        put(map, "dataKind", safe(() -> String.valueOf(attr.getDataKind())));
        put(map, "maxLength", safe(attr::getMaxLength));
        put(map, "precision", safe(attr::getPrecision));
        put(map, "scale", safe(attr::getScale));
        put(map, "required", safe(() -> ((DBSAttributeBase) attr).isRequired(), false));
        put(map, "autoGenerated", safe(() -> ((DBSAttributeBase) attr).isAutoGenerated(), false));
        put(map, "defaultValue", safe(attr::getDefaultValue));
        put(map, "description", safe(attr::getDescription));
        return map;
    }

    static Map<String, Object> describeConstraint(DBSEntityConstraint constraint, DBRProgressMonitor monitor) {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("name", constraint.getName());
        put(map, "type", safe(() -> constraint.getConstraintType().getId()));
        put(map, "typeName", safe(() -> constraint.getConstraintType().getName()));
        if (constraint instanceof DBSEntityReferrer referrer) {
            List<String> columns = new ArrayList<>();
            try {
                List<? extends DBSEntityAttributeRef> refs = referrer.getAttributeReferences(monitor);
                if (refs != null) {
                    for (DBSEntityAttributeRef ref : refs) {
                        if (ref != null && ref.getAttribute() != null) {
                            columns.add(ref.getAttribute().getName());
                        }
                    }
                }
            } catch (Exception e) {
                LOG.error("Cannot read columns of constraint '" + constraint.getName() + "'", e);
                map.put("warnings", List.of("Constraint columns could not be read: " + message(e)));
            }
            map.put("columns", columns);
        }
        if (constraint instanceof DBSEntityAssociation association) {
            put(map, "referencedTable", safe(() -> {
                DBSEntity target = association.getAssociatedEntity();
                return target != null ? DBUtils.getObjectFullId(target) : null;
            }));
            put(map, "referencedConstraint", safe(() -> {
                DBSEntityConstraint target = association.getReferencedConstraint();
                return target != null ? target.getName() : null;
            }));
        }
        return map;
    }

    static Map<String, Object> describeIndex(DBSTableIndex index, DBRProgressMonitor monitor) {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("name", index.getName());
        put(map, "unique", safe(index::isUnique, false));
        put(map, "primary", safe(index::isPrimary, false));
        put(map, "indexType", safe(() -> String.valueOf(index.getIndexType())));
        List<String> columns = new ArrayList<>();
        try {
            List<? extends DBSEntityAttributeRef> refs = index.getAttributeReferences(monitor);
            if (refs != null) {
                for (DBSEntityAttributeRef ref : refs) {
                    if (ref != null && ref.getAttribute() != null) {
                        columns.add(ref.getAttribute().getName());
                    }
                }
            }
        } catch (Exception e) {
            LOG.error("Cannot read columns of index '" + index.getName() + "'", e);
            map.put("warnings", List.of("Index columns could not be read: " + message(e)));
        }
        map.put("columns", columns);
        return map;
    }

    static String catalogName(DBSObject object) {
        for (DBSObject current = object.getParentObject(); current != null; current = current.getParentObject()) {
            if (current instanceof DBSCatalog) {
                return current.getName();
            }
        }
        return null;
    }

    static String schemaName(DBSObject object) {
        for (DBSObject current = object.getParentObject(); current != null; current = current.getParentObject()) {
            if (current instanceof DBSSchema) {
                return current.getName();
            }
        }
        return null;
    }

    static Map<String, Object> describeProcedure(DBSProcedure procedure, DBRProgressMonitor monitor) {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("name", procedure.getName());
        put(map, "type", safe(() -> String.valueOf(procedure.getProcedureType())));
        put(map, "description", safe(procedure::getDescription));
        List<Map<String, Object>> params = new ArrayList<>();
        try {
            Collection<? extends DBSProcedureParameter> raw = procedure.getParameters(monitor);
            if (raw != null) {
                for (DBSProcedureParameter param : raw) {
                    if (param == null) {
                        continue;
                    }
                    Map<String, Object> p = new LinkedHashMap<>();
                    p.put("name", param.getName());
                    put(p, "kind", safe(() -> String.valueOf(param.getParameterKind())));
                    put(p, "type", safe(() -> param.getParameterType().getTypeName()));
                    put(p, "fullType", safe(() -> param.getParameterType().getFullTypeName()));
                    params.add(p);
                }
            }
        } catch (Exception e) {
            LOG.error("Cannot read parameters of '" + procedure.getName() + "'", e);
            map.put("warnings", List.of("Procedure parameters could not be read: " + message(e)));
        }
        map.put("parameters", params);
        map.put("sourceAvailable", procedure instanceof DBPScriptObject);
        return map;
    }

    private interface SafeGet<T> {
        T get() throws Exception;
    }

    private static <T> T safe(SafeGet<T> getter) {
        return safe(getter, null);
    }

    private static <T> T safe(SafeGet<T> getter, T fallback) {
        try {
            T value = getter.get();
            return value != null ? value : fallback;
        } catch (Exception e) {
            return fallback;
        }
    }

    private static void put(Map<String, Object> map, String key, Object value) {
        if (value != null) {
            map.put(key, value);
        }
    }

    private static String message(Throwable e) {
        String message = e.getMessage();
        if (message == null || message.isBlank()) {
            return e.getClass().getSimpleName();
        }
        return message;
    }
}
